version: '3'
services:
  web:
    build:
      context: https://github.com/fruitcake514/cvescanner.git
      dockerfile: dockerfile
    network_mode: bridge  # This allows the container to access the host's network
    ports:
      - "5000:5000"  # This maps port 5000 from the container to port 5000 on the host
    volumes:
      - scan_data:/app/data  # Volume for persistent scan data
      - smtp_data:/app/smtp  # Volume for persistent SMTP data

volumes:
  scan_data:
  smtp_data:
